#pragma once
#include <windows.h>

// REGISTRY
DECLSPEC_IMPORT LSTATUS ADVAPI32$RegCreateKeyExW(HKEY, LPCWSTR, DWORD, LPWSTR, DWORD, REGSAM, LPSECURITY_ATTRIBUTES, PHKEY, LPDWORD);
DECLSPEC_IMPORT LSTATUS ADVAPI32$RegSetValueExW(HKEY, LPCWSTR, DWORD, DWORD, const BYTE*, DWORD);
DECLSPEC_IMPORT LSTATUS ADVAPI32$RegCloseKey(HKEY);
DECLSPEC_IMPORT LONG ADVAPI32$RegOpenKeyExW(HKEY, LPCWSTR, DWORD, REGSAM, PHKEY);
DECLSPEC_IMPORT LONG ADVAPI32$RegDeleteValueW(HKEY, LPCWSTR);

// FILE
DECLSPEC_IMPORT DWORD KERNEL32$GetTempPathW(DWORD, LPWSTR);
DECLSPEC_IMPORT UINT  KERNEL32$GetTempFileNameW(LPCWSTR, LPCWSTR, UINT, LPWSTR);
DECLSPEC_IMPORT HANDLE KERNEL32$CreateFileW(LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
DECLSPEC_IMPORT BOOL   KERNEL32$DeleteFileW(LPCWSTR);
DECLSPEC_IMPORT BOOL   KERNEL32$CloseHandle(HANDLE);

// SERVICE
DECLSPEC_IMPORT SC_HANDLE WINAPI ADVAPI32$OpenSCManagerW(LPCWSTR, LPCWSTR, DWORD);
DECLSPEC_IMPORT SC_HANDLE WINAPI ADVAPI32$OpenServiceW(SC_HANDLE, LPCWSTR, DWORD);
DECLSPEC_IMPORT BOOL WINAPI ADVAPI32$QueryServiceStatusEx(SC_HANDLE, SC_STATUS_TYPE, LPBYTE, DWORD, LPDWORD);
DECLSPEC_IMPORT BOOL WINAPI ADVAPI32$CloseServiceHandle(SC_HANDLE);

// ENCRYPTION
DECLSPEC_IMPORT BOOL WINAPI ADVAPI32$EncryptFileW(LPCWSTR lpFileName);
